<?xml version="1.0" encoding="iso-8859-1"?>
<!--
      Copyright (c) 2003 - 2017 Trading Technologies International
                  All Rights Reserved Worldwide

        * * *   S T R I C T L Y   P R O P R I E T A R Y   * * *

The following source code, and the ideas, expressions and concepts
incorporated therein, as well as the ideas, expressions and concepts
of any other material (whether tangible or intangible) disclosed in
conjunction with this source code, are the exclusive and proprietary
property, and constitutes confidential information, of Trading
Technologies International. Accordingly, the user of this source code
agrees that it shall continue to be bound by the terms and conditions
of any and all confidentiality agreements executed with Trading
Technologies International concerning the disclosure of the source code
and any other materials in conjunction therewith.

$Source: aconfig.xml $
$Date: 2017/05/10 15:09:05CDT $
$Revision: 2.31.1.14 $

-->
<!--

    This file contains information about configuration variables as
    well as the values of any "global"-scope (propagated to other
    machines) variables. It is automatically propagated among
    machines with GuardServers.

    aconfig_local.xml contains the values of "local"-scoped variables,
    and is not propagated automatically.

    DO NOT change any information in this file as per published TT
    documentation or as directed by TT Support.

    Programmer's Note: If you make *any* changes to this DTD, you must
    make corresponding changes to the code that reads it.

-->

<!DOCTYPE agile-config [
<!ELEMENT agile-config (config-schema, aenums, erelations, config-values)>
    <!-- the config-schema has all the metadata about the config -->
    <!ELEMENT config-schema (value-specs)>
        <!--
          "dn" means "distinguished name", the dot-notation
          hierarchical specification of a configuration value.
        -->
        <!ELEMENT value-specs (value-spec+)>
            <!ELEMENT value-spec (description, scope?,
                                  type-spec, default-value?)>
              <!--the dn_spec is like a dn, but can contain wildcards.
                  certain fields can have references to the substituted
                  value (\1, \2,...,etc.) -->
              <!ATTLIST value-spec dn_spec CDATA #REQUIRED>
                <!ELEMENT description (#PCDATA)>
                <!ELEMENT scope (local-scope|global-scope)>
                    <!ELEMENT local-scope EMPTY>
                    <!ELEMENT global-scope EMPTY>
                <!ELEMENT type-spec (bool-type     |
                                     int-type      |
                                     string-type)>
                    <!ELEMENT bool-type EMPTY>
                    <!ELEMENT int-type EMPTY>
                      <!ATTLIST int-type min_limit CDATA "none"
                                         max_limit CDATA "none" >
                    <!ELEMENT string-type EMPTY>
                <!--end type-spec-->
                <!ELEMENT default-value (#PCDATA)>
        <!--end value-specs-->
<!--
    <!ELEMENT aenum-stream (via_streamed_data?)>
        <!ELEMENT via_streamed_data (compound|atom)+>
        <!ELEMENT compound (compound|atom)*>
        <!ATTLIST compound name CDATA #IMPLIED
                           type CDATA #REQUIRED>
        <!ELEMENT atom EMPTY>
        <!ATTLIST atom name CDATA #IMPLIED
                       type CDATA #REQUIRED
                       value CDATA #REQUIRED>
-->

    <!ELEMENT aenums (aenum*)>
        <!ELEMENT aenum (aenumerant*)> <!-- zero means unregister -->
          <!ATTLIST aenum name CDATA #REQUIRED>
            <!ELEMENT aenumerant EMPTY>
              <!ATTLIST aenumerant value  CDATA #IMPLIED
                                   auxstr CDATA #REQUIRED>


    <!ELEMENT erelations (erelation*)>
        <!ELEMENT erelation (erelation-item*)> <!-- zero means unregister -->
          <!ATTLIST erelation name CDATA #REQUIRED>
            <!ELEMENT erelation-item EMPTY>
              <!ATTLIST erelation-item lhs CDATA #REQUIRED
                                       rhs CDATA #REQUIRED>


    <!ELEMENT config-values (config-value)*>
        <!ELEMENT config-value (group_values|value)>
          <!ATTLIST config-value dn ID #REQUIRED>
            <!ELEMENT group_values (group,value)+>
                <!ELEMENT group (#PCDATA)> <!--single group name-->
                <!ELEMENT value (#PCDATA)>

]>


<agile-config>
<config-schema>
<value-specs>
<!--____________________________RevisionCount________________________________-->
<value-spec dn_spec="AConfig.Meta.RevisionCount">
    <description>Incremented each time a change is made to this file programatically. You should also increment this if you make a change to this file manually.</description>
    <scope><global-scope/></scope>
    <type-spec>
        <int-type min_limit="-1"/>
    </type-spec>
    <default-value>-1</default-value>
</value-spec>

<!--_________________________Synthetic Custom Routing Table__________________________-->
  <value-spec dn_spec="AConfig.Core.Server.Synthetic-Specific.Uses-Custom-Routing-Table">
    <description>Setting indicating whether Synthetic servers are using a custom routing table.</description>
    <scope>
      <global-scope/>
    </scope>
    <type-spec>
      <bool-type/>
    </type-spec>
    <default-value>true</default-value>
  </value-spec>
  
<!--______________________Synthetic Throttle Time_____________________________________________-->
	<value-spec dn_spec="AConfig.Core.Server.Synthetic-Specific.EnableSyntheticUnicastThrottle">
		<description>Enable Synthetic Unicast Throttling. Only for AlgoSE and SSE.</description>
		<scope><local-scope/></scope>
		<type-spec> <bool-type/> </type-spec>
		<default-value>true</default-value>
	</value-spec>
	<value-spec dn_spec="AConfig.Core.Server.Synthetic-Specific.SyntheticUnicastThrottleInterval">
		<description>Throttle Synthetic Unicast Time. Only for AlgoSE and SSE.</description>
		<scope><local-scope/></scope>
		<type-spec> <int-type/> </type-spec>
		<default-value>10</default-value>
	</value-spec>
  
<!--________________________Main Configdir___________________________________-->
<value-spec dn_spec="AConfig.Core.ConfigDir">
    <description>Location of configuration files</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>invalid</default-value>
</value-spec>

<!--_____________________________Logfiledir__________________________________-->
<value-spec dn_spec="AConfig.Core.LogfileDir">
    <description>Location of log files</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>invalid</default-value>
</value-spec>

<!--_____________________________Datfiledir__________________________________-->
<value-spec dn_spec="AConfig.Core.DatfileDir">
    <description>Location of data files</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>invalid</default-value>
</value-spec>

<!--_____________________________Auditfiledir________________________________-->
<value-spec dn_spec="AConfig.Core.AuditfileDir">
    <description>Location of audit files</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>invalid</default-value>
</value-spec>

<!--_____________________________ProxyOverride__________________________________-->
<value-spec dn_spec="AConfig.Core.ProxyOverride">
    <description>Location of data files</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>invalid</default-value>
</value-spec>

<!--________________________MiniDump Type_________________________________-->
<value-spec dn_spec="AConfig.Core.MiniDumpType">
    <description>Type of mini dump to generate 0 = stack only, 1 = stack + globals</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>0</default-value>
</value-spec>

<!--____________________________TT Log File Severity Level________________________________-->
<value-spec dn_spec="AConfig.Core.LoggingSeverityLevel.TTLogFile">
	<description>Used to adjust the amount of data sent to the log files 2 is the default value. Lower Numbers mean less data.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<int-type/>
	</type-spec>
	<default-value>2</default-value>
</value-spec>



<!--____________________________App Specific Log File Severity Level________________________________-->
<value-spec dn_spec="AConfig.Core.LoggingSeverityLevel.AppSpecificLogFile">
	<description>Used to adjust the amount of data sent to the log files 2 is the default value. Lower Numbers mean less data.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<int-type/>
	</type-spec>
	<default-value>2</default-value>
</value-spec>



<!--____________________________TTSIM Local Mode________________________________-->
<value-spec dn_spec="AConfig.Core.SimLocal">
    <description>Used to indicate if TTSIM Local mode is on.</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--________________________CLIENT___________________________________________-->
<!--________________________CLIENT___________________________________________-->
<!--________________________CLIENT___________________________________________-->
<!--________________________CLIENT___________________________________________-->
<!--________________________CLIENT___________________________________________-->


<!--_________________________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Fill.Debug-Flags.GAL">
    <description>Gateway Attribute List request state machine debug</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--_________________________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Order.Debug-Flags.GAL">
    <description>Gateway Attribute List request state machine debug</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--_________________________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Servers-Use-MPF">
	<description>Obsolete - No longer used.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<bool-type/>
	</type-spec>
	<default-value>false</default-value>
</value-spec>



<!--_________________________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Debug-Flags.GAL">
    <description>Gateway Attribute List request state machine debug</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--_________________________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.AckTimer">
	<description>Sets the time delay (in milliseconds) before the price api requests the next packet.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<int-type/>
	</type-spec>
	<default-value>5</default-value>
</value-spec>



<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Proxy-Subscription-Threshold">
	<description>Indicates the number of outstanding subscription requests the client can make to price proxys before queuing up subscriptions so as to not overload the system. Do not modify this setting unless instructed to do so by TT Support.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<int-type/>
	</type-spec>
	<default-value>4</default-value>
</value-spec>



<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.TokenEnabled">
    <description>A value of true instructs the client to attach a product/price token in its contract download request to the price server or price proxy server. Do not modify this setting unless instructed to do so by TT Support.</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>true</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Server-Subscription-Threshold">
	<description>Indicates the number of outstanding subscription requests the client can make to price servers before queuing up subscriptions so as to not overload the system. Do not modify this setting unless instructed to do so by TT Support.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<int-type/>
	</type-spec>
	<default-value>1</default-value>
</value-spec>



<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.PFX-Subscription-Threshold">
    <description>Indicates the number of outstanding subscription requests the client can make to price servers operating in PFX mode before queuing up subscriptions so as to not overload the system. Do not modify this setting unless instructed to do so by TT Support.</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>2</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Request-Threshold">
	<description>Indicates the number of outstanding requests the client can make to price servers before queuing up requests so as to not overload the system. Do not modify this setting unless instructed to do so by TT Support. Do not modify this setting unless instructed to do so by TT Support.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<int-type/>
	</type-spec>
	<default-value>20</default-value>
</value-spec>



<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.TTAPI-Depth-Rerequest-Delay">
    <description>Indicates the number of seconds to wait after rerequesting depth to resolve a missed packet before sending additional depth snapshot requests to a TTAPI server.</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>10</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Synchronized-Snapshot-Timeout">
    <description>Amount of time, expressed in milliseconds, the client will wait for TradeData packets before timing out when doing sychronized price subscription. Applies only to subscription requests on PFX servers. Do not modify this setting unless instructed to do so by TT Support.</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>2000</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Refresh-Request-Timeout">
    <description>Amount of time, expressed in milliseconds, the client will wait for price refresh requests to complete. Valid settings are 1000 or greater. Do not modify this setting unless instructed to do so by TT Support.</description>
    <scope>
        <local-scope/>
    </scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>100000</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Depth-Request-Timeout">
    <description>Amount of time, expressed in milliseconds, the client will wait for depth requests to complete. Valid settings are 1000 or greater. Do not modify this setting unless instructed to do so by TT Support.</description>
    <scope>
        <local-scope/>
    </scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>200000</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Send-Price-Proxy-Keep-Alives">
    <description>Indicates if the Price Proxy should send keep alive messages to each back-end MPF, in addition to normal heartbeats. By default this is turned off, as heartbeats are sufficient in most networks. Do not modify this setting unless instructed to do so by TT Support.</description>
    <scope>
        <local-scope/>
    </scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Send-Price-Proxy-Repeated-Text-Messages">
    <description>Indicates if the Price Proxy should repeate text messages sent from the MPF/APF price servers to connected clients.</description>
    <scope>
        <local-scope/>
    </scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>true</default-value>
</value-spec>

<!--______________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Client.API-Specific.Price.Enable-PriceVariance-Logging">
    <description>Enables additional INFO level logging of price reasonability checks. A value of "false" will enable additional information only in DEBUG logging mode.</description>
    <scope>
        <local-scope/>
    </scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>true</default-value>
</value-spec>

<!--________________________MESSAGING________________________________________-->
<!--________________________MESSAGING________________________________________-->
<!--________________________MESSAGING________________________________________-->
<!--________________________MESSAGING________________________________________-->
<!--________________________MESSAGING________________________________________-->
<!--________________________MESSAGING________________________________________-->

<!--________________________Daemon-Address___________________________________-->

<!-- you substitute "Local" or "Remote" for the wildcard -->
<value-spec dn_spec="AConfig.Core.Messaging.Proximity-Specific.[Proximity_Choices].Daemon-Address">
    <description>Specifies the TTM daemon address to connect to for $1 connections. Comma-delimited, can contain hostname, IP address, or "loopback"</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <default-value>default</default-value>
</value-spec>


<!--________________________Daemon-Port______________________________________-->

<!-- you substitute "Local" or "Remote" for the wildcard -->
<value-spec dn_spec="AConfig.Core.Messaging.Proximity-Specific.[Proximity_Choices].Daemon-Port">
    <description>Specifies the TTM daemon port(s) to connect to for $1 connections. Comma-delimited, must be as many as in ".Daemon" setting. "default" is acceptable.</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!--formerly DEFAULT_DPORT -->
    <default-value>10200</default-value>
</value-spec>




<!--________________________Interface________________________________________-->

<!-- you substitute "Local" or "Remote" for the wildcard -->
<value-spec dn_spec="AConfig.Core.Messaging.Proximity-Specific.[Proximity_Choices].Interface">
    <description>Specifies the networking interface(s) that TTM is supposed to use for $1 connections. Comma-delimited. "default" and "loopback" are acceptable.</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <default-value>default</default-value>
</value-spec>

<!--________________________Multicast-Group__________________________________-->
<!-- you substitute "Local" or "Remote" for the wildcard -->
<value-spec dn_spec="AConfig.Core.Messaging.Proximity-Specific.[Proximity_Choices].Multicast-Group">
    <description>Obsolete - No longer used.</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly DEFAULT_MCAST_NET -->
    <default-value>239.255.3.10</default-value>
</value-spec>

<!--_________________________________________________________________________-->
<!--_________________________________________________________________________-->
<!--_______________________SERVICES__________________________________________-->
<!--_________________________________________________________________________-->

<!--_______________________Production Default Service________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Production.Default">
    <description>TTM Service to use as the "Default" service for production environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly DEFAULT_SERVICE -->
    <default-value>8900</default-value>
</value-spec>
<!--_______________________Production Price Service__________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Production.Price">
    <description>TTM Service to use as the "Price" service for production environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly PRICE_SERVICE -->
    <default-value>8901</default-value>
</value-spec>
<!--_______________________Production Order Service_________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Production.Order">
    <description>TTM Service to use as the "Order" service for production environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly ORDER_SERVICE -->
    <default-value>8902</default-value>
</value-spec>
<!--_______________________Production Status Service__________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Production.Status">
    <description>TTM Service to use as the "Status" service for production environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly STATUS_SERVICE -->
    <default-value>8900</default-value>
</value-spec>
<!--_______________________Simulation Default Service________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Simulation.Default">
    <description>TTM Service to use as the "Default" service for simulation environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly DEFAULT_SERVICE -->
    <default-value>8910</default-value>
</value-spec>
<!--_______________________Simulation Price Service__________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Simulation.Price">
    <description>TTM Service to use as the "Price" service for simulation environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly PRICE_SERVICE_SIM -->
    <default-value>8911</default-value>
</value-spec>
<!--_______________________Simulation Order Service_________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Simulation.Order">
    <description>TTM Service to use as the "Order" service for simulation environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly ORDER_SERVICE_SIM -->
    <default-value>8912</default-value>
</value-spec>

<!--_______________________Simulation Status Service__________________________-->
<value-spec dn_spec="AConfig.Core.Messaging.Service.Simulation.Status">
    <description>TTM Service to use as the "Status" service for simulation environments</description>
    <scope><local-scope/></scope>
    <type-spec> <string-type/> </type-spec>
    <!-- formerly STATUS_SERVICE_SIM -->
    <default-value>8910</default-value>
</value-spec>


<!--________________________GuardConfigDir___________________________________-->
<value-spec dn_spec="AConfig.Core.Guard.ConfigDir">
    <description>Directory for guardian/guardserver configuration files</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>invalid</default-value>
</value-spec>

<!--________________________Guardian Enable Daemon Setup_________________________-->
<value-spec dn_spec="AConfig.Core.Guard.Guardian.EnableDaemonSetupGUI">
	<description>Determines whether the 'Daemon Setup' option under the Config menu item of Guardian is enabled or grayed out. Some applications e.g. TTRelay want to configure Daemon setup manually as opposed to through the Guardian GUI.</description>
	<scope><local-scope/></scope>
	<type-spec>
		<bool-type/>
	</type-spec>
	<default-value>true</default-value>
</value-spec>



<!--________________________Guardian Heartbeat Debug_____________________________-->
<value-spec dn_spec="AConfig.Core.Guard.Guardian.Debug.HB-Debug">
    <description>Debug guardian heartbeats</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--________________________Guardian Heartbeat Debug Number of HBs_______________-->
<value-spec dn_spec="AConfig.Core.Guard.Guardian.Debug.HB-Generate">
    <description>Debug guardian heartbeats - number of heartbeats</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>0</default-value>
</value-spec>

<!--________________________Gateway Filters Simulation_____________________________-->
<value-spec dn_spec="AConfig.Core.Guard.Guardian.GatewayFilterSIM">
    <description>Gateway filters for simulation environment</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value><!--empty--></default-value>
</value-spec>

<!--________________________Gateway Filters Production_____________________________-->
<value-spec dn_spec="AConfig.Core.Guard.Guardian.GatewayFilterPROD">
    <description>Gateway filters for production environment</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value><!--empty--></default-value>
</value-spec>

<!--________________________Guardian Ping IP_________________________________-->
<value-spec dn_spec="AConfig.Core.Guard.Guardian.RemoteSessionIP">
    <description>If Guardian is running on a remote session box, provide the IP that Guardian should respond to Guardian Ping's with.</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value><!--empty--></default-value>
</value-spec>

<!--________________________GuardServer Heartbeat Debug__________________________-->
<value-spec dn_spec="AConfig.Core.Guard.GuardServer.Debug.HB-Debug">
    <description>Debug guardserver heartbeats</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--________________________GuardServer Heartbeat Debug Number of HBs____________-->
<value-spec dn_spec="AConfig.Core.Guard.GuardServer.Debug.HB-Generate">
    <description>Debug guardserver heartbeats - number of heartbeats</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>0</default-value>
</value-spec>

<!--________________________GuardServer LM Debug_________________________________-->
<value-spec dn_spec="AConfig.Core.Guard.GuardServer.Debug.LM-Debug">
    <description>Debug guardserver LM</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--___________________________CheckLogins___________________________________-->

<value-spec dn_spec="AConfig.Core.Guard.GuardServer.Security.Check-Logins">
    <description>Should guardserver check user logins on this workstation? specify "always", "never", or "use_login_type".</description>
    <scope><local-scope/></scope>
    <type-spec>
        <string-type/>
    </type-spec>
    <default-value>always</default-value>
</value-spec>

<!--________________________GuardServer Proxy Mode_________________________________-->
<value-spec dn_spec="AConfig.Core.Guard.GuardServer.ProxyMode">
    <description>If in proxy mode, HB exchange ID's found in the ProxyMode.lic file in addition to exchanges found in the license file</description>
    <scope><local-scope/></scope>
    <type-spec>
        <bool-type/>
    </type-spec>
    <default-value>false</default-value>
</value-spec>

<!--_________________________________________________________________________-->
<value-spec dn_spec="AConfig.Core.Guard.Thread.Priority">
    <description>Generic thread priority</description>
    <scope><local-scope/></scope>
    <type-spec>
        <int-type/>
    </type-spec>
    <default-value>2</default-value>
</value-spec>

<!--___________________________Environment___________________________________-->

<value-spec dn_spec="AConfig.Core.Guard.Environment">
    <description>Operating environment: simulation or production</description>